trainer:
    accelerator : 'gpu'
    precision: 16-mixed
    min_epochs: 6
    max_epochs: 100
    benchmark: True
    log_every_n_steps: 10
learning:
    model: "unet"
    loss: "ce"
    backbone: "resnet18"
    weights: True  # imagenet weights
    in_channels: 5  # Sentinel 2
    num_classes: 6
    lr: 1e-3
    patience: 5
    ignore_index: -1
datamodule:
    dataset: "potsdam"
    root_dir: "/home/kno/datasets/postdam/Potsdam/"
    train_coordinate_file_path: "coord_files/potsdam_train_coordinate_list.txt"
    training_sample_perct: 1.0  # percentage
    val_image_file_path: "coord_files/potsdam_val_image_list.txt"
    batch_size: 4
    num_workers: 4
    patch_size: 256
